package helpers

// STORAGE_LOCAL ..
const STORAGE_LOCAL = "local"

// STORAGE_AWS ..
const STORAGE_AWS = "aws"

// STORAGE_GOOGLE ..
const STORAGE_GOOGLE = "google"

// IMAGE_LARGE_QUALITY ..
const IMAGE_LARGE_QUALITY = "large"

// IMAGE_ORIGINAL ..
const IMAGE_ORIGINAL = "IMAGE_ORIGINAL"

// IMAGE_VERY_LARGE_QUALITY ..
const IMAGE_VERY_LARGE_QUALITY = "very-large"

// IMAGE_MEDIUM_QUALITY ..
const IMAGE_MEDIUM_QUALITY = "medium"

// IMAGE_SMALL_QUALITY ..
const IMAGE_SMALL_QUALITY = "small"

// IMAGE_VERY_SMALL_QUALITY ..
const IMAGE_VERY_SMALL_QUALITY = "very-small"

var IMAGE_QUALITIES = []string{STORAGE_LOCAL, STORAGE_AWS, STORAGE_GOOGLE, IMAGE_LARGE_QUALITY, IMAGE_ORIGINAL, IMAGE_VERY_LARGE_QUALITY, IMAGE_MEDIUM_QUALITY, IMAGE_SMALL_QUALITY, IMAGE_VERY_SMALL_QUALITY}
