language: go
go:
  - "1.15"

addons:
  ssh_known_hosts: 
    - 192.53.174.157
  apt:
    packages:
    - imagick
    - vips
    - rsync

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avHPe "sshpass -p$DOMAINESIA_SSH_PASSWORD ssh -p$DOMAINESIA_SSH_PORT" ./ $DOMAINESIA_SSH_USER@$DOMAINESIA_SSH_HOST:/home/nugroho2/playground/gofilestatic
  on:
    branch: master
