language: go
go:
  - "1.15"

before_install:
  - wget https://www.imagemagick.org/download/ImageMagick.tar.gz
  - tar xvzf ImageMagick.tar.gz && cd ImageMagick-7.0.8-26
  - ./configure
  - make
  - make install
  - ldconfig /usr/local/lib
  - magick -version

addons:
  ssh_known_hosts:
    - nugrohosamiyono.com:64000
  apt:
    packages:
      - ssh
      - sshpass
      - rsync
      - vips

before_script:
  - cp deploy/domainesia/.gitignore.domainesia .gitignore
  - cp deploy/domainesia/script.sh.domainesia deploy/domainesia/script.sh  
  - chmod +x deploy/domainesia/script.sh
  - cp deploy/domainesia/restart-app.sh.domainesia deploy/domainesia/restart-app.sh  
  - chmod +x deploy/domainesia/restart-app.sh
  - rm -rf .git

deploy:
  provider: script
  cleanup: false
  script: bash deploy/domainesia/script.sh
  on:
    branch: master
